export const SOURCES = {
  enem: {
    label: "Matriz de referência · INEP",
    url: "https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem/outros-documentos",
  },
  essay: {
    label: "Cartilha da redação 2026 · INEP",
    url: "https://www.gov.br/inep/pt-br/centrais-de-conteudo/acervo-linha-editorial/publicacoes-institucionais/avaliacoes-e-exames-da-educacao-basica/a-redacao-do-enem-2026-cartilha-do-a-participante",
  },
  pmpe: {
    label: "Edital PM-PE · Soldado · 2023",
    url: "https://dhg1h5j42swfq.cloudfront.net/2023/11/11081005/edital-pm-pe.pdf",
  },
  constitution: {
    label: "Constituição Federal · Planalto",
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
  },
  rights: {
    label: "Declaração Universal · ONU",
    url: "https://www.un.org/en/about-us/universal-declaration-of-human-rights",
  },
};
export const TRACKS = {
  enem: {
    name: "ENEM",
    subtitle: "Seu próximo passo é a universidade.",
    tag: "ENSINO SUPERIOR",
    description: "As quatro áreas do conhecimento e um espaço só para a sua redação.",
    reference: SOURCES.enem,
  },
  pmpe: {
    name: "PM-PE",
    subtitle: "Preparação com direção e disciplina.",
    tag: "CARREIRA POLICIAL",
    description:
      "Preparação inicial para Soldado, com referência no edital de 2023. Confira futuras atualizações do concurso.",
    reference: SOURCES.pmpe,
  },
};
export const SUBJECTS = [
  {
    id: "matematica",
    track: "enem",
    name: "Matemática",
    icon: "Calculator",
    color: "blue",
    description: "Números que fazem sentido no cotidiano.",
  },
  {
    id: "linguagens",
    track: "enem",
    name: "Linguagens",
    icon: "Languages",
    color: "purple",
    description: "Leia o mundo além das palavras.",
  },
  {
    id: "natureza",
    track: "enem",
    name: "Ciências da Natureza",
    icon: "Atom",
    color: "green",
    description: "Conecte fenômenos, vida e transformação.",
  },
  {
    id: "humanas",
    track: "enem",
    name: "Ciências Humanas",
    icon: "Globe2",
    color: "orange",
    description: "Entenda a sociedade no tempo e no espaço.",
  },
  {
    id: "portugues",
    track: "pmpe",
    name: "Língua Portuguesa",
    icon: "Languages",
    color: "purple",
    description: "Interpretação, sintaxe e uso da língua.",
  },
  {
    id: "historia-pe",
    track: "pmpe",
    name: "História de Pernambuco",
    icon: "Landmark",
    color: "orange",
    description: "Formação, movimentos e identidade.",
  },
  {
    id: "logica",
    track: "pmpe",
    name: "Raciocínio Lógico",
    icon: "Calculator",
    color: "blue",
    description: "Argumentos, contagem e probabilidade.",
  },
  {
    id: "informatica",
    track: "pmpe",
    name: "Informática",
    icon: "Monitor",
    color: "green",
    description: "Segurança, internet e ferramentas digitais.",
  },
  {
    id: "constitucional",
    track: "pmpe",
    name: "Direito Constitucional",
    icon: "Scale",
    color: "blue",
    description: "Princípios e organização constitucional.",
  },
  {
    id: "direitos-humanos",
    track: "pmpe",
    name: "Direitos Humanos",
    icon: "HeartHandshake",
    color: "purple",
    description: "Dignidade, igualdade e proteção.",
  },
];
// Conteúdo didático autoral introdutório. Não são questões oficiais nem reprodução de provas.
const lessons = [
  [
    "porcentagem",
    "matematica",
    "Porcentagem sem complicação",
    "Razão, proporção e variação percentual",
    20,
    [
      "Porcentagem é uma razão com denominador 100. Para calcular p% de uma quantidade Q, multiplique Q por p/100. Antes de fazer uma conta, identifique a base: a pergunta é “porcentagem de quê?”. O mesmo valor absoluto pode representar percentuais diferentes quando a base muda.",
      "Em aumentos e descontos sucessivos, multiplique fatores. Um aumento de 20% corresponde ao fator 1,20; um desconto de 20%, ao fator 0,80. Os percentuais não se anulam, pois a segunda alteração ocorre sobre uma nova base. Para comparar preços, calcule o valor final de cada oferta.",
      "Na regra de três, descubra se as grandezas são diretas ou inversas. Mais produtos com preço unitário fixo implicam maior custo: proporção direta. Mais trabalhadores igualmente produtivos para uma mesma tarefa podem reduzir o tempo: proporção inversa, desde que as demais condições permaneçam iguais.",
    ],
    "Um livro de R$ 80 recebe desconto de 15%: 80 × 0,85 = R$ 68. Com um aumento posterior de 15%, passa a 68 × 1,15 = R$ 78,20.",
    "Percentuais sucessivos são multiplicados como fatores; não simplesmente somados.",
  ],
  [
    "funcoes",
    "matematica",
    "Funções no dia a dia",
    "Função afim, taxa de variação e gráficos",
    25,
    [
      "Uma função associa cada valor de entrada a um único valor de saída. Na função afim f(x) = ax + b, a representa a taxa de variação e b é o valor quando x = 0. Em um gráfico, b é a interseção com o eixo vertical; a é a variação vertical dividida pela variação horizontal.",
      "Se a for positivo, a função é crescente; se negativo, decrescente; se zero, constante. Duas tarifas podem ser comparadas igualando suas expressões. O resultado indica a quantidade em que os custos se igualam; antes e depois desse ponto, verifique qual tarifa é menor.",
      "Nem todo problema admite qualquer número real. Se x representa quantidade de ingressos, o domínio relevante contém inteiros não negativos. Em gráficos, leia unidades, escalas e recortes dos eixos: uma diferença visual grande pode representar uma mudança numérica pequena.",
    ],
    "Um transporte cobra R$ 6 fixos e R$ 2 por quilômetro: C(x) = 2x + 6. Para 8 km, C(8) = R$ 22.",
    "Identifique primeiro o custo fixo, a taxa e a unidade da variável.",
  ],
  [
    "estatistica",
    "matematica",
    "Estatística e probabilidade",
    "Média, mediana e chance de eventos",
    25,
    [
      "A média aritmética soma os valores e divide pelo número de observações. Na média ponderada, cada valor é multiplicado pelo seu peso; a soma desses produtos é dividida pela soma dos pesos. Valores extremos podem deslocar a média sem representar a experiência da maioria.",
      "A mediana é o valor central após ordenar os dados. Com número par de observações, use a média dos dois centrais. A moda é o valor mais frequente e pode não ser única. Escolha a medida de acordo com o problema, especialmente em distribuições de renda ou tempos com valores muito altos.",
      "Em um espaço amostral finito com resultados igualmente prováveis, P(A) = casos favoráveis / casos possíveis. Eventos independentes permitem multiplicar probabilidades. Sem reposição, o espaço amostral muda a cada retirada; por isso, as probabilidades precisam ser recalculadas.",
    ],
    "Nos valores 2, 3, 3, 4 e 18, a média é 6, a mediana é 3 e a moda é 3. O valor 18 eleva a média.",
    "Ordene antes de achar a mediana e confira se os resultados são equiprováveis.",
  ],
  [
    "interpretacao",
    "linguagens",
    "Ler, inferir, interpretar",
    "Informações explícitas e implícitas",
    20,
    [
      "Informação explícita está diretamente expressa no texto. Inferência é uma conclusão sustentada por pistas, não um palpite livre. Ao resolver uma questão, localize o trecho relevante e observe relações de causa, consequência, oposição e condição.",
      "O sentido de uma palavra depende do contexto. Ironia pode criar distância entre o que se diz literalmente e a avaliação pretendida. Textos multimodais combinam imagem, palavra, posição e cor; interpretar apenas a legenda pode omitir a informação principal.",
      "Elimine alternativas que generalizam além do texto. Expressões como “sempre”, “todos” e “nunca” exigem sustentação forte. Diferencie a voz do autor da fala de personagens ou de opiniões citadas. A resposta deve respeitar o texto, mesmo quando você tem outra opinião sobre o tema.",
    ],
    "“A biblioteca fechou mais tarde e, ainda assim, não comportou todos.” A expressão “ainda assim” sinaliza que ampliar o horário não foi suficiente.",
    "Justifique cada inferência com uma pista concreta do texto.",
  ],
  [
    "variacao",
    "linguagens",
    "A língua em movimento",
    "Variação linguística e adequação",
    20,
    [
      "A língua varia conforme região, grupo social, época e situação comunicativa. Variedades linguísticas têm regularidades próprias. A norma-padrão é uma referência importante em contextos formais, mas não transforma outras variedades em ausência de regras.",
      "Adequação significa escolher recursos para uma situação. Uma conversa entre amigos, um artigo acadêmico e uma mensagem institucional podem mobilizar vocabulário e construções diferentes. Reconhecer variação não impede aprender a escrita formal; amplia o repertório de comunicação.",
      "O preconceito linguístico ocorre quando se inferioriza uma pessoa ou grupo pela sua fala. Em textos literários, marcas de oralidade podem construir identidade e caracterização. Não atribua automaticamente falta de conhecimento a personagens que utilizam uma variedade regional.",
    ],
    "“Tu vais”, “tu vai” e “você vai” podem ocorrer em variedades brasileiras distintas. Em uma tarefa que pede norma-padrão, observe a concordância prevista para o pronome empregado.",
    "A pergunta pode avaliar adequação ao contexto, e não apenas regra gramatical.",
  ],
  [
    "generos",
    "linguagens",
    "Gêneros e argumentação",
    "Propósito comunicativo e construção de argumentos",
    20,
    [
      "Gênero textual é uma forma social de comunicação, como notícia, crônica, artigo de opinião ou propaganda. Tipos textuais são modos de organização, como narração, descrição, exposição e argumentação. Um gênero pode combinar vários tipos.",
      "No artigo de opinião, identifique a tese defendida e as razões apresentadas. Dados, exemplos e referências podem sustentar o raciocínio, mas sua presença não garante validade. Verifique se a evidência é pertinente à conclusão e se o argumento evita generalizações indevidas.",
      "Na publicidade, comandos no imperativo, apelo emocional e escolhas visuais frequentemente procuram influenciar comportamentos. Em uma notícia, diferencie fatos relatados de avaliações atribuídas a fontes. O suporte e o público ajudam a explicar as escolhas de linguagem.",
    ],
    "“A cidade deve ampliar ciclovias, pois deslocamentos curtos podem ser feitos de bicicleta.” A proposta é a tese; a razão introduzida por “pois” é um argumento.",
    "Separe o que o autor defende de como ele tenta convencer o leitor.",
  ],
  [
    "ecologia",
    "natureza",
    "Ecologia e equilíbrio",
    "Energia, cadeias alimentares e impactos",
    25,
    [
      "Em cadeias alimentares, produtores transformam energia luminosa ou química em matéria orgânica. Consumidores obtêm energia ao se alimentar de outros seres. Decompositores participam da transformação da matéria orgânica e da disponibilização de nutrientes no ambiente.",
      "A energia flui e diminui ao longo dos níveis tróficos, pois parte é utilizada no metabolismo e dissipada como calor. A matéria, em contraste, participa de ciclos biogeoquímicos. Não confunda transferência de energia com reciclagem de nutrientes.",
      "Na eutrofização, o excesso de nutrientes pode favorecer proliferação de algas. A decomposição da biomassa aumenta o consumo de oxigênio dissolvido e pode provocar morte de organismos aquáticos. Analise a sequência de causas antes de escolher medidas de controle.",
    ],
    "Capim → gafanhoto → sapo → serpente. O capim é produtor; o gafanhoto, consumidor primário. A disponibilidade energética tende a diminuir ao longo da cadeia.",
    "Energia flui; matéria circula. Intervenções precisam enfrentar a causa do desequilíbrio.",
  ],
  [
    "energia",
    "natureza",
    "Energia elétrica na prática",
    "Potência, consumo e eficiência",
    25,
    [
      "Potência indica a taxa de transformação de energia. A relação E = P × t permite calcular consumo quando a potência é constante. Se P está em quilowatts e t em horas, o resultado é dado em quilowatt-hora, unidade de energia usada em contas de eletricidade.",
      "Um equipamento de 1.000 W tem potência de 1 kW. Um aparelho muito potente usado por pouco tempo pode consumir menos que um aparelho de menor potência ligado o dia todo. Compare potência e tempo antes de decidir onde economizar.",
      "Eficiência relaciona energia útil e energia total recebida. Nem toda energia elétrica se converte no efeito desejado. Para estudar circuitos resistivos, use U = R × I e P = U × I, observando volts, ohms, ampères e watts. Modelos ideais são aproximações das condições reais.",
    ],
    "Um chuveiro de 5,5 kW usado 20 minutos por dia durante 30 dias funciona 10 horas e consome 55 kWh.",
    "Converta minutos em horas antes de calcular o consumo em kWh.",
  ],
  [
    "solucoes",
    "natureza",
    "Química das soluções",
    "Concentração e diluição",
    25,
    [
      "Solução é uma mistura homogênea. Soluto é a substância dissolvida e solvente é o meio em que ocorre a dissolução. A concentração em massa relaciona massa de soluto e volume de solução: C = m/V. Expresse as unidades de maneira consistente.",
      "Diluir significa adicionar solvente sem adicionar soluto. Quando não há reação nem perda de material, a massa de soluto permanece constante: C₁V₁ = C₂V₂. O volume da relação é o volume final da solução, não apenas o volume de solvente acrescentado.",
      "A concentração molar utiliza quantidade de matéria em mol por litro. Para converter massa em quantidade de matéria, divida pela massa molar. Em problemas ambientais, valores de concentração só fazem sentido quando comparados na mesma unidade e sob as condições indicadas no enunciado.",
    ],
    "Dissolver 10 g em volume final de 2 L produz concentração de 5 g/L. Ao aumentar o volume total para 4 L, a concentração passa a 2,5 g/L.",
    "Na diluição, conserve a quantidade de soluto e acompanhe o volume final.",
  ],
  [
    "industrializacao",
    "humanas",
    "Industrialização e trabalho",
    "Transformações produtivas e sociais",
    25,
    [
      "A industrialização articulou máquinas, fontes de energia e novas formas de organizar o trabalho. A expansão das fábricas contribuiu para a urbanização e para mudanças nas relações entre trabalhadores e proprietários. Esses processos ocorreram de modo desigual entre regiões.",
      "A divisão de tarefas e o controle do tempo alteraram a experiência do trabalho. No fordismo, a linha de montagem favorece produção padronizada em grande escala. A padronização não significa ausência de conflitos: condições de trabalho e remuneração motivaram organização coletiva.",
      "Ao analisar documentos históricos, identifique autoria, contexto, interesses e público. Uma propaganda industrial e um relato operário podem descrever a mesma época a partir de perspectivas distintas. Evite projetar automaticamente valores atuais sobre agentes de outros períodos.",
    ],
    "Uma fábrica que divide a montagem de um produto em operações repetidas aumenta a especialização das tarefas e reduz a autonomia de cada trabalhador sobre o produto completo.",
    "Relacione inovação técnica com mudanças sociais e formas de poder.",
  ],
  [
    "urbanizacao",
    "humanas",
    "Cidade, território e desigualdade",
    "Urbanização e segregação socioespacial",
    20,
    [
      "Urbanização é o crescimento da participação da população urbana no total, e não apenas o aumento físico de uma cidade. Industrialização, migrações, serviços e transformações no campo podem contribuir para esse processo.",
      "Segregação socioespacial envolve distribuição desigual de grupos e oportunidades no território. Moradia distante de empregos, equipamentos de saúde e transporte confiável aumenta custos e tempos de deslocamento. A localização é uma dimensão do acesso a direitos.",
      "Problemas urbanos exigem leitura integrada: impermeabilização do solo, ocupação de áreas vulneráveis e drenagem insuficiente podem agravar enchentes. Não atribua fenômenos complexos a uma única causa ou responsabilize apenas os moradores, ignorando políticas públicas e acesso à terra.",
    ],
    "Duas pessoas percorrem 15 km até o trabalho. Uma leva 20 minutos e outra 90. Distância semelhante não implica acesso equivalente à cidade.",
    "Observe redes, serviços e desigualdades, além dos limites no mapa.",
  ],
  [
    "cidadania",
    "humanas",
    "Cidadania e participação",
    "Democracia, direitos e vida coletiva",
    20,
    [
      "Cidadania envolve direitos e participação na vida coletiva. Direitos civis se relacionam a liberdades e proteção jurídica; políticos, à participação no poder; sociais, a condições de vida como educação e trabalho. A classificação ajuda a estudar processos históricos, mas esses direitos são interdependentes.",
      "A democracia exige mais que votação periódica. Pluralismo, liberdade de expressão, instituições e possibilidade de contestação permitem participação e controle do poder. Movimentos sociais podem inserir demandas antes excluídas no debate público.",
      "Ao comparar correntes filosóficas, identifique a pergunta central e as razões de cada posição. Uma afirmação normativa discute como algo deve ser; uma descrição relata como algo é. Reconhecer essa diferença evita tratar uma preferência política como constatação factual.",
    ],
    "Um conselho público que reúne governo e sociedade cria um canal de participação. Seu funcionamento efetivo depende de informação, representação e capacidade de influenciar decisões.",
    "Diferencie direito formal, acesso concreto e participação nas decisões.",
  ],
  [
    "coesao",
    "portugues",
    "Interpretação e coesão",
    "Conectivos, referência e sentido",
    25,
    [
      "Coesão reúne mecanismos que ligam partes de um texto: pronomes, repetição controlada, substituições lexicais e conectivos. Coerência é a construção de sentido global. Um texto pode conter conectivos e ainda apresentar contradições de conteúdo.",
      "Conectivos indicam relações semânticas. “Embora” introduz concessão; “portanto”, conclusão; “porque”, frequentemente causa ou explicação. Substituir um conectivo por outro altera o sentido se a relação lógica não for preservada.",
      "Para identificar o referente de um pronome, leia o período completo. Proximidade não é o único critério: gênero, número e sentido também importam. Em períodos longos, separe orações para reconhecer sujeitos, ações e relações entre as informações.",
    ],
    "“Embora tivesse estudado, ficou nervosa.” A concessão apresenta um fato que poderia levar à expectativa contrária, sem impedir a ação principal.",
    "Reconstrua a relação entre as orações antes de trocar o conectivo.",
  ],
  [
    "concordancia",
    "portugues",
    "Concordância e crase",
    "Regras essenciais para a prova",
    25,
    [
      "Em regra, o verbo concorda com o sujeito em número e pessoa. Localize o núcleo do sujeito antes de escolher a flexão. Termos intercalados e complementos longos podem afastar visualmente sujeito e verbo, mas não alteram essa relação.",
      "O verbo “haver” com sentido de existir é impessoal e permanece no singular. “Fazer” indicando tempo decorrido também é impessoal. Já “existir” possui sujeito e concorda com ele. Compare “Havia muitas dúvidas” com “Existiam muitas dúvidas”.",
      "Crase é a fusão da preposição a com outro a, como o artigo feminino. Verifique se o termo anterior exige preposição e se o seguinte aceita artigo. Antes de verbo, em regra, não há artigo feminino e não ocorre crase. O teste com um termo masculino pode ajudar: se surgir “ao”, há indício de “à” na construção feminina equivalente.",
    ],
    "“Dirigiu-se à biblioteca”: dirigir-se exige a; biblioteca aceita a. “Começou a estudar”: antes do verbo estudar não há artigo feminino.",
    "Encontre o sujeito e a regência antes de confiar na sonoridade da frase.",
  ],
  [
    "pernambuco-colonia",
    "historia-pe",
    "Pernambuco colonial",
    "Açúcar, sociedade e presença holandesa",
    25,
    [
      "A produção açucareira marcou a colonização de Pernambuco. Engenhos articulavam terra, trabalho escravizado, crédito e comércio atlântico. Esse sistema gerou riqueza concentrada e profundas desigualdades, além de resistência por parte dos grupos submetidos à exploração.",
      "Olinda e Recife ocuparam posições diferentes na organização colonial: a primeira se vinculou fortemente aos interesses senhoriais; a segunda ganhou importância portuária e comercial. Essas diferenças ajudam a compreender disputas de poder, sem reduzir toda a sociedade a apenas dois grupos.",
      "A ocupação holandesa em parte do Nordeste se relacionou às disputas do comércio atlântico e do açúcar. No governo de Nassau, ocorreram intervenções urbanas e produção de registros artísticos e científicos. A resistência ao domínio holandês culminou em sua expulsão de Pernambuco em 1654.",
    ],
    "Ao interpretar uma imagem de engenho, observe quem realiza o trabalho, quem controla a produção e como o produto se conecta ao comércio externo.",
    "Vincule a economia açucareira à escravidão, ao comércio e às relações de poder.",
  ],
  [
    "revolucoes-pe",
    "historia-pe",
    "Movimentos pernambucanos",
    "1817, 1824 e disputas políticas",
    25,
    [
      "A Revolução Pernambucana de 1817 expressou insatisfações políticas e econômicas com o poder monárquico. O movimento apresentou projeto republicano e foi reprimido. Seus participantes não formavam um bloco social homogêneo, e os limites de suas propostas precisam ser considerados.",
      "A Confederação do Equador, em 1824, ocorreu no contexto de contestação à centralização do poder imperial. Defendia uma organização republicana e federativa, em oposição ao rumo autoritário associado ao governo de D. Pedro I.",
      "A Revolução Praieira, de 1848, reuniu disputas provinciais e demandas políticas e sociais. Ao estudar os movimentos, organize uma linha do tempo com contexto, participantes, reivindicações e resultado. Não confunda a posição de cada movimento em relação à independência de 1822.",
    ],
    "1817 antecede a independência do Brasil; 1824 é posterior e envolve oposição ao governo imperial. A cronologia muda o sentido político da contestação.",
    "Datas ajudam a localizar o contexto; a prova também exige causas e projetos.",
  ],
  [
    "proposicoes",
    "logica",
    "Proposições e conectivos",
    "Negação e equivalência lógica",
    25,
    [
      "Proposição é uma sentença declarativa à qual se pode atribuir valor verdadeiro ou falso. Perguntas e ordens, em geral, não são proposições. Em lógica, interessa a estrutura da afirmação, independentemente de concordarmos com seu conteúdo.",
      "A conjunção “p e q” é verdadeira apenas se ambas forem verdadeiras. A disjunção inclusiva “p ou q” é falsa apenas se ambas forem falsas. A condicional “se p, então q” é falsa somente quando p é verdadeira e q é falsa.",
      "Pelas leis de De Morgan, negar “p e q” resulta em “não p ou não q”; negar “p ou q” resulta em “não p e não q”. A condicional p → q equivale a “não p ou q” e à contrapositiva “não q → não p”. A recíproca q → p não é uma equivalência geral.",
    ],
    "Negar “Ana estuda e Bruno trabalha” produz “Ana não estuda ou Bruno não trabalha”. Basta uma parte ser falsa para a conjunção ser falsa.",
    "Negar uma condicional resulta em p e não q.",
  ],
  [
    "contagem",
    "logica",
    "Contagem e probabilidade",
    "Escolhas sucessivas e combinações",
    25,
    [
      "Pelo princípio multiplicativo, escolhas sucessivas com m e n possibilidades geram m × n resultados, quando cada escolha da primeira etapa admite as n opções da segunda. Restrições, como proibição de repetição, alteram o número de opções seguintes.",
      "Permutações ordenam todos os elementos. Combinações selecionam subconjuntos em que a ordem não importa. Antes de escolher uma fórmula, pergunte se trocar a ordem produz um resultado diferente. Formar uma comissão difere de definir presidente e vice.",
      "A probabilidade clássica relaciona casos favoráveis e possíveis quando os resultados são equiprováveis. Em retiradas sem reposição, diminui o total de objetos e pode diminuir o número de favoráveis. Explicite cada etapa para evitar multiplicar frações incompatíveis.",
    ],
    "Uma senha de duas letras distintas usando A, B e C admite 3 × 2 = 6 possibilidades. Já escolher duas dessas letras sem ordem produz apenas 3 pares.",
    "Ordem e repetição determinam como contar.",
  ],
  [
    "seguranca",
    "informatica",
    "Segurança digital e internet",
    "Phishing, autenticação e cópias de segurança",
    20,
    [
      "Phishing é uma tentativa de enganar pessoas para obter informações ou induzir ações, frequentemente usando mensagens que imitam organizações. Urgência artificial, domínios parecidos e pedidos inesperados de credenciais são sinais de atenção. Um cadeado HTTPS protege a conexão, mas não garante honestidade do site.",
      "A autenticação em múltiplos fatores combina categorias diferentes, como algo que você sabe e algo que possui. Duas senhas não representam necessariamente dois fatores distintos. Não compartilhe códigos temporários; confirme solicitações por um canal conhecido.",
      "Backup é uma cópia para recuperação. Sincronização pode replicar exclusões ou arquivos corrompidos e, sozinha, não substitui uma estratégia de cópias com versões. Atualizações corrigem falhas, e o princípio do menor privilégio limita o acesso ao necessário para a tarefa.",
    ],
    "Uma mensagem pede para “regularizar a conta agora”. Em vez de abrir o link, acesse o endereço oficial conhecido e verifique a situação diretamente.",
    "Segurança depende da origem da solicitação, do acesso concedido e da recuperação dos dados.",
  ],
  [
    "planilhas",
    "informatica",
    "Planilhas e organização de dados",
    "Referências, fórmulas e arquivos",
    20,
    [
      "Uma planilha organiza dados em linhas e colunas. Uma referência como B2 identifica a célula na coluna B e linha 2. Fórmulas começam com = e podem combinar operadores, funções e referências. O resultado depende dos valores referenciados e da ordem das operações.",
      "Referências relativas mudam ao copiar uma fórmula. Referências absolutas usam cifrões para fixar coluna e linha, como $B$2. Referências mistas fixam apenas uma parte: $B2 mantém a coluna; B$2 mantém a linha.",
      "SOMA agrega valores numéricos e MÉDIA calcula a média aritmética dos valores considerados pela função. Filtrar oculta temporariamente linhas que não atendem a critérios; ordenar muda a disposição. Ao ordenar dados relacionados, mantenha a tabela inteira para não desvincular nomes e valores.",
    ],
    "Ao copiar =A2*$B$1 de C2 para C3, a fórmula passa a =A3*$B$1. A linha da quantidade varia, mas o fator em B1 permanece fixo.",
    "Diferencie copiar valores, copiar fórmulas e mover referências.",
  ],
  [
    "principios",
    "constitucional",
    "Princípios fundamentais",
    "Estado, poderes e fundamentos",
    25,
    [
      "A Constituição organiza o Estado e estabelece direitos e limites ao poder. O artigo 1º apresenta fundamentos da República, como soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e da livre iniciativa e pluralismo político. Estude a redação vigente na fonte oficial.",
      "Fundamentos não se confundem com objetivos fundamentais do artigo 3º, como construir uma sociedade livre, justa e solidária e reduzir desigualdades. Também não se confundem com princípios das relações internacionais, tratados no artigo 4º.",
      "O artigo 2º trata dos Poderes Legislativo, Executivo e Judiciário como independentes e harmônicos. A separação de funções envolve mecanismos de controle recíproco. Para questões objetivas, compare o termo solicitado com o dispositivo correto antes de avaliar as alternativas.",
    ],
    "“Dignidade da pessoa humana” é fundamento. “Erradicar a pobreza e a marginalização” integra os objetivos fundamentais. A classificação é parte da resposta.",
    "Monte um quadro com fundamentos, objetivos e princípios internacionais.",
    "constitution",
  ],
  [
    "garantias",
    "constitucional",
    "Direitos e garantias",
    "Liberdades e instrumentos de proteção",
    25,
    [
      "Direitos enunciam bens e posições protegidos; garantias oferecem instrumentos para sua proteção. O artigo 5º reúne direitos e deveres individuais e coletivos. Ler apenas resumos pode ocultar condições e exceções, por isso compare o material com o texto constitucional.",
      "O habeas corpus protege a liberdade de locomoção diante de violência ou coação por ilegalidade ou abuso de poder. O habeas data se relaciona ao conhecimento e à retificação de informações pessoais em registros governamentais ou de caráter público, nas hipóteses constitucionais.",
      "O mandado de segurança protege direito líquido e certo, não amparado por habeas corpus ou habeas data, quando presentes os requisitos constitucionais. Ao resolver questões, identifique primeiro o bem protegido; depois, verifique quem pratica o ato e as condições do instrumento.",
    ],
    "Se o enunciado destaca ameaça ilegal à liberdade de ir e vir, o instrumento constitucional associado é o habeas corpus, e não o habeas data.",
    "Associe cada garantia ao direito protegido, sem apagar seus requisitos.",
    "constitution",
  ],
  [
    "dignidade",
    "direitos-humanos",
    "Dignidade e direitos humanos",
    "Universalidade e proteção das pessoas",
    25,
    [
      "Direitos humanos buscam proteger a dignidade das pessoas. Universalidade significa que sua titularidade não depende de nacionalidade, origem, religião ou outra condição pessoal. Indivisibilidade e interdependência apontam que diferentes direitos se relacionam e não devem ser tratados como compartimentos isolados.",
      "A Declaração Universal dos Direitos Humanos foi proclamada pela Assembleia Geral da ONU em 1948. É um marco internacional que articula liberdades, igualdade, participação e direitos sociais. Estude seu contexto posterior à Segunda Guerra Mundial e diferencie declaração de tratado.",
      "A proteção de direitos exige considerar desigualdades concretas e barreiras de acesso. Igualdade não é justificativa para ignorar necessidades distintas. Na atuação estatal, dignidade e não discriminação orientam o tratamento das pessoas; a condição de suspeito não elimina a titularidade de direitos.",
    ],
    "Impedir acesso a um serviço apenas pela origem é incompatível com a universalidade e a não discriminação. Critérios de atendimento precisam de justificativa adequada.",
    "Direitos pertencem às pessoas; não são um prêmio por comportamento.",
    "rights",
  ],
  [
    "protecao",
    "direitos-humanos",
    "Proteção e não discriminação",
    "Direitos, grupos e atuação pública",
    20,
    [
      "A proteção de crianças, adolescentes, pessoas idosas e pessoas com deficiência considera barreiras e vulnerabilidades específicas. Medidas de proteção não negam a universalidade dos direitos: procuram tornar seu exercício efetivo.",
      "No estudo da legislação extravagante, organize cada lei por finalidade, condutas tratadas e requisitos. O edital de referência inclui, entre outros temas, crimes no ECA e legislação sobre abuso de autoridade e tortura. Este capítulo é introdutório; a leitura da lei vigente é necessária para aprofundamento.",
      "Não conclua que toda irregularidade administrativa configura automaticamente um tipo penal. Questões jurídicas exigem observar os elementos descritos na norma e no enunciado. Em exercícios de direitos humanos, diferencie prevenção, responsabilização e reparação: são respostas com funções distintas.",
    ],
    "Acessibilidade em um prédio público remove barreiras ao exercício de direitos. Não se trata apenas de permitir entrada, mas de viabilizar uso autônomo e seguro dos serviços.",
    "Leia requisitos e exceções na fonte oficial antes de generalizar uma regra.",
    "constitution",
  ],
];
export const LESSONS = lessons.map(
  ([id, subject, title, subtitle, minutes, paragraphs, example, takeaway, source]) => ({
    id,
    subject,
    title,
    subtitle,
    minutes,
    paragraphs,
    example,
    takeaway,
    track: SUBJECTS.find((s) => s.id === subject).track,
    source: SOURCES[source || SUBJECTS.find((s) => s.id === subject).track],
  }),
);
export const ESSAY_THEMES = [
  {
    id: "leitura",
    title: "Caminhos para democratizar o acesso à leitura no Brasil",
    axis: "Educação e cultura",
    prompts: [
      "Bibliotecas e espaços de leitura podem aproximar livros de comunidades que enfrentam barreiras econômicas e territoriais.",
      "O acesso envolve disponibilidade de obras, acessibilidade e mediação: ter um livro por perto não elimina todas as dificuldades de leitura.",
    ],
    questions: [
      "Quais barreiras dificultam o acesso?",
      "Como escola, poder público e comunidade podem atuar?",
    ],
  },
  {
    id: "digital",
    title: "Desafios para a inclusão digital da população idosa",
    axis: "Tecnologia e cidadania",
    prompts: [
      "Serviços essenciais passaram a oferecer atendimento digital, o que pode simplificar tarefas e também criar barreiras.",
      "A inclusão envolve conexão, equipamentos acessíveis e formação para o uso autônomo e seguro.",
    ],
    questions: [
      "O que diferencia acesso e participação digital?",
      "Que ação promove autonomia e evita exclusão?",
    ],
  },
  {
    id: "ambiental",
    title: "Caminhos para fortalecer a educação ambiental nas cidades",
    axis: "Ambiente e sociedade",
    prompts: [
      "Problemas como descarte irregular de resíduos e ocupação de áreas vulneráveis envolvem hábitos individuais e decisões coletivas.",
      "A educação ambiental pode articular conhecimento, participação comunitária e cobrança de políticas públicas.",
    ],
    questions: [
      "Como conectar aprendizagem e realidade local?",
      "Quais atores podem executar uma intervenção?",
    ],
  },
];
export const ESSAY_COMPETENCIES = [
  ["Norma escrita", "Revise concordância, pontuação, ortografia e construção dos períodos."],
  [
    "Tema e repertório",
    "Responda ao recorte proposto e conecte referências pertinentes ao argumento.",
  ],
  ["Argumentação", "Apresente uma tese e desenvolva razões claras, com exemplos e explicações."],
  ["Coesão", "Conecte ideias e parágrafos com recursos adequados, evitando repetições mecânicas."],
  [
    "Intervenção",
    "Proponha ação, agente, meio e finalidade, com detalhamento e respeito aos direitos humanos.",
  ],
];
