import { LESSONS } from "./catalog.js";
import { EXPANDED_QUESTIONS } from "./expanded-content.js";
import { VARIABLE_QUESTIONS } from "./variable-questions.js";
const rows = [
  [
    "porcentagem",
    1,
    "Uma mochila de R$ 160 recebe desconto de 25%. Qual é o preço final?",
    ["R$ 40", "R$ 120", "R$ 135", "R$ 140", "R$ 200"],
    1,
    "25% de 160 são 40. Subtraindo o desconto: 160 − 40 = R$ 120. Também podemos multiplicar 160 por 0,75.",
  ],
  [
    "porcentagem",
    2,
    "Um produto custa R$ 200. Após um aumento de 10% e um desconto de 10% sobre o novo preço, seu valor é:",
    ["R$ 180", "R$ 198", "R$ 200", "R$ 202", "R$ 220"],
    1,
    "As bases são diferentes: 200 × 1,10 × 0,90 = 198. A variação total é uma redução de 1%, e não zero.",
  ],
  [
    "funcoes",
    1,
    "Uma locadora cobra R$ 30 fixos mais R$ 12 por hora de uso. Quanto custa alugar por 4 horas?",
    ["R$ 42", "R$ 48", "R$ 72", "R$ 78", "R$ 120"],
    3,
    "A função do custo é C(h) = 30 + 12h. Para h = 4, o resultado é 30 + 48 = R$ 78.",
  ],
  [
    "funcoes",
    2,
    "Os planos A e B custam, respectivamente, A(x) = 20 + 3x e B(x) = 40 + 2x. Para qual x os custos são iguais?",
    ["10", "15", "20", "30", "40"],
    2,
    "Igualando: 20 + 3x = 40 + 2x. Subtraindo 2x e 20 dos dois lados, x = 20. Ambos custam R$ 80 nesse ponto.",
  ],
  [
    "estatistica",
    1,
    "Os tempos de espera, em minutos, foram 3, 5, 7, 9 e 21. Qual é a mediana?",
    ["5", "7", "9", "10", "21"],
    1,
    "Os valores já estão ordenados. Com cinco observações, a mediana é o terceiro valor: 7. A média, que é 9, não foi solicitada.",
  ],
  [
    "estatistica",
    2,
    "Uma caixa tem 3 fichas azuis e 2 vermelhas. Retiram-se duas fichas sem reposição. Qual a probabilidade de ambas serem azuis?",
    ["3/10", "9/25", "2/5", "3/5", "1/5"],
    0,
    "A primeira azul tem chance 3/5. Depois restam duas azuis em quatro fichas: 2/4. Multiplicando, 3/5 × 2/4 = 3/10.",
  ],
  [
    "interpretacao",
    1,
    "Leia: “O bairro ganhou uma biblioteca. Mesmo assim, os moradores ainda percorrem longas distâncias para encontrar livros acessíveis.” A expressão “mesmo assim” estabelece:",
    [
      "Uma conclusão inevitável",
      "Uma enumeração",
      "Um contraste com a expectativa",
      "Uma condição",
      "Uma comparação de tamanhos",
    ],
    2,
    "Esperava-se que a biblioteca resolvesse o problema de acesso. A expressão introduz um fato que contraria essa expectativa, sem negar a existência da biblioteca.",
  ],
  [
    "interpretacao",
    2,
    "Em uma campanha, lê-se: “Uma torneira pingando não grita. Mas pede atenção.” O recurso central da segunda frase é:",
    [
      "Uso exclusivamente literal",
      "Atribuição de ação humana a um objeto",
      "Citação de pesquisa estatística",
      "Definição técnica de torneira",
      "Descrição sem intenção persuasiva",
    ],
    1,
    "“Pedir atenção” é uma ação humana atribuída à torneira. A personificação contribui para sensibilizar o leitor sobre desperdício.",
  ],
  [
    "variacao",
    1,
    "Uma personagem usa expressões regionais em uma crônica. Essa escolha pode ter a função de:",
    [
      "Provar que sua fala não tem regras",
      "Eliminar o contexto social",
      "Caracterizar sua identidade e seu meio",
      "Impedir qualquer interpretação",
      "Substituir todos os recursos narrativos",
    ],
    2,
    "Marcas regionais podem construir identidade, ambientação e voz. Variação linguística não equivale à ausência de regras.",
  ],
  [
    "variacao",
    2,
    "Uma pessoa escreve de modo informal aos amigos e formal em um requerimento. Isso exemplifica:",
    [
      "Incapacidade de usar a língua",
      "Adequação à situação comunicativa",
      "Desaparecimento das variedades",
      "Uso obrigatório de linguagem literária",
      "Preconceito linguístico em toda situação",
    ],
    1,
    "A escolha de registro considera destinatário, finalidade e contexto. Alternar registros pode demonstrar domínio de diferentes recursos da língua.",
  ],
  [
    "generos",
    1,
    "Qual trecho apresenta uma tese, e não apenas um dado descritivo?",
    [
      "A reunião começou às 10h.",
      "O parque tem duas entradas.",
      "A cidade deveria ampliar as bibliotecas públicas.",
      "Foram distribuídos 100 formulários.",
      "A escola fica na avenida principal.",
    ],
    2,
    "“Deveria ampliar” expressa uma posição defendida pelo autor. Os demais trechos relatam informações descritivas.",
  ],
  [
    "generos",
    2,
    "Um anúncio usa “Experimente hoje” ao lado da imagem de um produto. O imperativo contribui principalmente para:",
    [
      "Situar um evento histórico",
      "Induzir o leitor a uma ação",
      "Apresentar uma prova científica",
      "Garantir neutralidade",
      "Definir uma palavra",
    ],
    1,
    "O imperativo dirige-se ao leitor e procura influenciar seu comportamento. É um recurso persuasivo, não uma garantia da qualidade anunciada.",
  ],
  [
    "ecologia",
    1,
    "Na cadeia capim → gafanhoto → sapo, o gafanhoto é:",
    [
      "Produtor",
      "Consumidor primário",
      "Consumidor secundário",
      "Decompositor obrigatório",
      "Consumidor terciário",
    ],
    1,
    "O gafanhoto se alimenta diretamente do produtor, ocupando o nível de consumidor primário. O sapo é consumidor secundário nessa cadeia.",
  ],
  [
    "ecologia",
    2,
    "Após receber grande quantidade de nutrientes, um lago apresenta proliferação de algas e posterior redução do oxigênio dissolvido. Uma explicação para a redução é:",
    [
      "Ausência completa de microrganismos",
      "Maior decomposição da matéria orgânica",
      "Conversão de toda água em sal",
      "Interrupção do metabolismo dos decompositores",
      "Aumento ilimitado de oxigênio pela respiração",
    ],
    1,
    "A decomposição da biomassa por organismos aeróbios consome oxigênio dissolvido. Esse processo ajuda a explicar a mortandade de peixes na eutrofização.",
  ],
  [
    "energia",
    1,
    "Um aparelho de 2 kW fica ligado por 3 horas. Seu consumo é:",
    ["0,67 kWh", "1,5 kWh", "5 kWh", "6 kWh", "6 kW"],
    3,
    "Energia = potência × tempo: 2 kW × 3 h = 6 kWh. kW é unidade de potência, não de energia consumida.",
  ],
  [
    "energia",
    2,
    "Um chuveiro de 6.000 W é usado por 10 minutos por dia durante 30 dias. Qual é o consumo mensal?",
    ["3 kWh", "18 kWh", "30 kWh", "60 kWh", "300 kWh"],
    2,
    "6.000 W = 6 kW. O uso total é 300 minutos, ou 5 horas. O consumo é 6 × 5 = 30 kWh.",
  ],
  [
    "solucoes",
    1,
    "Uma solução contém 12 g de soluto em volume final de 3 L. Sua concentração em massa é:",
    ["0,25 g/L", "4 g/L", "9 g/L", "15 g/L", "36 g/L"],
    1,
    "C = m/V = 12/3 = 4 g/L. É necessário usar o volume da solução, e não a massa do solvente.",
  ],
  [
    "solucoes",
    2,
    "São diluídos 100 mL de uma solução de 20 g/L até volume final de 400 mL. A nova concentração é:",
    ["2 g/L", "4 g/L", "5 g/L", "10 g/L", "80 g/L"],
    2,
    "C₁V₁ = C₂V₂. Assim, 20 × 100 = C₂ × 400, resultando em 5 g/L. A quantidade de soluto foi conservada.",
  ],
  [
    "industrializacao",
    1,
    "Uma característica associada à linha de montagem fordista é:",
    [
      "Produção artesanal individual de todo o produto",
      "Padronização e divisão de tarefas",
      "Ausência de controle de tempo",
      "Fim da produção em escala",
      "Eliminação de máquinas",
    ],
    1,
    "A linha de montagem divide tarefas e organiza a produção padronizada em grande escala, frequentemente com ritmo controlado.",
  ],
  [
    "industrializacao",
    2,
    "Ao comparar uma propaganda de fábrica com o relato de um trabalhador da mesma época, o procedimento histórico adequado é:",
    [
      "Descartar o relato por ser pessoal",
      "Tratar a propaganda como descrição neutra",
      "Considerar autoria, contexto e interesses de ambos",
      "Escolher apenas o documento mais curto",
      "Ignorar a data dos documentos",
    ],
    2,
    "Toda fonte deve ser contextualizada. As perspectivas distintas podem revelar experiências, objetivos e relações sociais diferentes.",
  ],
  [
    "urbanizacao",
    1,
    "O crescimento da proporção de habitantes em áreas urbanas em relação à população total é chamado de:",
    ["Erosão", "Urbanização", "Rotação de culturas", "Desertificação", "Intemperismo"],
    1,
    "Urbanização diz respeito ao aumento relativo da população urbana. A expansão física de uma cidade, isoladamente, não define todo o processo.",
  ],
  [
    "urbanizacao",
    2,
    "Bairros periféricos com poucas linhas de transporte e longos trajetos até empregos evidenciam:",
    [
      "Acesso necessariamente igual à cidade",
      "Ausência de relação entre espaço e renda",
      "Uma dimensão da segregação socioespacial",
      "Fim das desigualdades urbanas",
      "Redução obrigatória do custo de deslocamento",
    ],
    2,
    "A distribuição desigual de serviços e oportunidades produz custos diferentes de acesso à cidade, inclusive em tempo e mobilidade.",
  ],
  [
    "cidadania",
    1,
    "A participação em eleições está diretamente associada a qual categoria de direitos?",
    [
      "Direitos políticos",
      "Apenas direitos de propriedade",
      "Direitos exclusivamente comerciais",
      "Somente direitos autorais",
      "Privilégios hereditários",
    ],
    0,
    "Direitos políticos dizem respeito à participação na organização e no exercício do poder, incluindo a participação eleitoral nas condições previstas.",
  ],
  [
    "cidadania",
    2,
    "Uma associação de moradores apresenta propostas em audiência pública. Essa atuação exemplifica:",
    [
      "Participação social em decisões coletivas",
      "Eliminação do debate democrático",
      "Substituição automática de todos os representantes",
      "Uma atividade necessariamente privada sem efeito público",
      "Ausência de cidadania",
    ],
    0,
    "Cidadania inclui participação por diferentes canais. Audiências permitem que demandas sejam apresentadas, embora não garantam por si sós sua adoção.",
  ],
  [
    "coesao",
    1,
    "Em “Estudou com regularidade; portanto, ampliou seu repertório”, o conectivo destacado exprime:",
    ["Oposição", "Conclusão", "Concessão", "Alternância", "Condição"],
    1,
    "“Portanto” apresenta uma conclusão decorrente da informação anterior. Trocar por “embora” alteraria a relação semântica.",
  ],
  [
    "coesao",
    2,
    "Em “Marina entregou a Ana o livro que havia comprado”, o pronome relativo “que” retoma:",
    ["Marina", "Ana", "O livro", "A entrega", "Nenhum termo"],
    2,
    "O relativo introduz uma oração que caracteriza “o livro”. O sentido é: Marina havia comprado o livro.",
  ],
  [
    "concordancia",
    1,
    "Qual frase atende à norma-padrão?",
    [
      "Haviam muitas pessoas na sala.",
      "Fazem dois anos que estudo.",
      "Existe várias possibilidades.",
      "Havia muitos candidatos preparados.",
      "Fazem muito tempo que não chove.",
    ],
    3,
    "“Haver” no sentido de existir é impessoal: havia muitos candidatos. “Fazer” indicando tempo decorrido também permanece no singular.",
  ],
  [
    "concordancia",
    2,
    "Em qual alternativa o uso da crase está correto?",
    [
      "Começou à estudar.",
      "Entregou o documento à uma pessoa.",
      "Dirigiu-se à biblioteca.",
      "Ficou frente à frente.",
      "Referiu-se à ele.",
    ],
    2,
    "“Dirigir-se” pede a preposição a, e “biblioteca” admite artigo a. Nas outras opções, verbo, artigo indefinido, expressão repetida e pronome pessoal impedem essa fusão.",
  ],
  [
    "pernambuco-colonia",
    1,
    "A economia açucareira colonial em Pernambuco esteve fortemente vinculada:",
    [
      "À inexistência de trabalho escravizado",
      "Ao comércio atlântico e à produção em engenhos",
      "Apenas ao consumo doméstico sem exportação",
      "À industrialização automobilística",
      "Ao fim da concentração fundiária",
    ],
    1,
    "Engenhos, grandes propriedades, trabalho escravizado e comércio atlântico constituíram elementos centrais da produção açucareira colonial.",
  ],
  [
    "pernambuco-colonia",
    2,
    "A presença holandesa em Pernambuco no século XVII deve ser relacionada principalmente:",
    [
      "À disputa por circuitos comerciais do açúcar",
      "À independência brasileira de 1822",
      "À Revolução Praieira de 1848",
      "À expansão do café no século XX",
      "Ao fim do comércio marítimo",
    ],
    0,
    "O domínio territorial esteve ligado a interesses econômicos e disputas atlânticas do período, especialmente os circuitos do açúcar.",
  ],
  [
    "revolucoes-pe",
    1,
    "A Revolução Pernambucana de 1817 apresentou um projeto de caráter:",
    [
      "Republicano",
      "Absolutista sem contestação",
      "Restaurador do domínio holandês",
      "Ligado à industrialização de 1950",
      "Favorável ao Estado Novo",
    ],
    0,
    "O movimento de 1817 apresentou projeto republicano e contestou o poder monárquico, embora reunisse participantes com interesses distintos.",
  ],
  [
    "revolucoes-pe",
    2,
    "A Confederação do Equador, em 1824, relacionou-se à oposição:",
    [
      "À centralização do poder no Primeiro Reinado",
      "À proclamação da República de 1889",
      "À Constituição de 1988",
      "Ao governo de Nassau",
      "À criação das capitanias hereditárias",
    ],
    0,
    "O movimento contestou a centralização imperial no governo de D. Pedro I e defendeu uma organização republicana e federativa.",
  ],
  [
    "proposicoes",
    1,
    "A negação de “Lia estuda e Rui trabalha” é:",
    [
      "Lia não estuda e Rui não trabalha",
      "Lia estuda ou Rui trabalha",
      "Lia não estuda ou Rui não trabalha",
      "Se Lia estuda, Rui trabalha",
      "Lia estuda e Rui não trabalha",
    ],
    2,
    "Pela lei de De Morgan, ¬(p ∧ q) equivale a ¬p ∨ ¬q. Não é necessário que ambas as partes sejam falsas.",
  ],
  [
    "proposicoes",
    3,
    "Qual proposição é logicamente equivalente a “Se estudo, então aprendo”?",
    [
      "Se aprendo, então estudo",
      "Se não estudo, então não aprendo",
      "Estudo e não aprendo",
      "Se não aprendo, então não estudo",
      "Não estudo e aprendo",
    ],
    3,
    "A contrapositiva ¬q → ¬p é equivalente à condicional p → q. A recíproca e a inversa não são equivalências gerais.",
  ],
  [
    "contagem",
    1,
    "Uma senha usa dois algarismos distintos escolhidos entre 1, 2, 3 e 4. Quantas senhas são possíveis?",
    ["4", "6", "8", "12", "16"],
    3,
    "São 4 escolhas para a primeira posição e 3 para a segunda, pois não pode repetir: 4 × 3 = 12.",
  ],
  [
    "contagem",
    3,
    "Uma comissão de 2 pessoas será escolhida entre 5 candidatos. Sem cargos distintos, quantas comissões são possíveis?",
    ["5", "10", "15", "20", "25"],
    1,
    "A ordem não importa. Contamos 5 × 4 pares ordenados e dividimos por 2: 10 comissões.",
  ],
  [
    "seguranca",
    1,
    "Receber uma mensagem urgente pedindo sua senha exige principalmente:",
    [
      "Enviar a senha para evitar bloqueio",
      "Conferir a solicitação por canal oficial conhecido",
      "Confiar apenas no logotipo",
      "Compartilhar também o código temporário",
      "Desativar as atualizações",
    ],
    1,
    "Logotipos e mensagens urgentes podem ser falsificados. Verificar por canal oficial evita depender do link fornecido pelo possível fraudador.",
  ],
  [
    "seguranca",
    2,
    "Qual afirmação sobre backup é correta?",
    [
      "Sincronização sempre impede perda por exclusão",
      "Backup e sincronização têm necessariamente o mesmo objetivo",
      "Uma cópia com versões pode permitir recuperar arquivos apagados",
      "Um único arquivo original já é um backup",
      "Backup elimina a necessidade de segurança de acesso",
    ],
    2,
    "Versões permitem recuperar estados anteriores. A sincronização pode propagar uma exclusão; não deve ser confundida automaticamente com backup.",
  ],
  [
    "planilhas",
    1,
    "Ao copiar =A2*$B$1 de C2 para C3, a fórmula resultante é:",
    ["=A2*$B$1", "=A3*$B$1", "=A3*$B$2", "=B2*$C$1", "=A2*$B$2"],
    1,
    "A2 é relativa e avança uma linha. $B$1 é absoluta e permanece fixa.",
  ],
  [
    "planilhas",
    2,
    "Em uma tabela, filtrar registros significa:",
    [
      "Apagar definitivamente as linhas excluídas do filtro",
      "Exibir apenas linhas que atendem ao critério, preservando os dados",
      "Transformar fórmulas em imagens",
      "Somar todas as colunas automaticamente",
      "Alterar necessariamente os valores das células",
    ],
    1,
    "Filtrar controla a exibição. Os registros que não atendem ao critério ficam ocultos até que o filtro seja alterado ou removido.",
  ],
  [
    "principios",
    1,
    "Qual alternativa apresenta um fundamento da República previsto no artigo 1º da Constituição?",
    [
      "Dignidade da pessoa humana",
      "Erradicação da pobreza",
      "Defesa da paz nas relações internacionais",
      "Concessão de asilo político",
      "Cooperação entre os povos",
    ],
    0,
    "A dignidade da pessoa humana é fundamento (art. 1º, III). As demais alternativas correspondem a objetivos ou princípios das relações internacionais.",
  ],
  [
    "principios",
    2,
    "Segundo o artigo 2º da Constituição, os Poderes da União são:",
    [
      "Apenas Executivo e Legislativo",
      "Legislativo, Executivo e Judiciário, independentes e harmônicos",
      "União, Estados e Municípios",
      "Polícia, Ministério Público e Exército",
      "Municípios, comarcas e tribunais",
    ],
    1,
    "A classificação de Poderes não se confunde com entes federativos nem com órgãos específicos. O art. 2º enuncia Legislativo, Executivo e Judiciário.",
  ],
  [
    "garantias",
    1,
    "A garantia constitucional associada à proteção contra coação ilegal à liberdade de locomoção é:",
    [
      "Habeas data",
      "Ação de cobrança",
      "Habeas corpus",
      "Recurso administrativo genérico",
      "Pedido de certidão",
    ],
    2,
    "O habeas corpus protege a liberdade de locomoção nas hipóteses do art. 5º, LXVIII, da Constituição.",
  ],
  [
    "garantias",
    2,
    "O habeas data se relaciona, nas hipóteses constitucionais:",
    [
      "À liberdade de locomoção exclusivamente",
      "Ao conhecimento e à retificação de informações pessoais em registros previstos na Constituição",
      "À substituição de qualquer recurso",
      "À criação de leis",
      "À revisão automática de tributos",
    ],
    1,
    "O art. 5º, LXXII, trata do conhecimento e da retificação de informações pessoais em registros governamentais ou de caráter público.",
  ],
  [
    "dignidade",
    1,
    "A universalidade dos direitos humanos indica que:",
    [
      "Somente nacionais são titulares",
      "Dependem da renda de cada pessoa",
      "Pertencem às pessoas independentemente de condições pessoais como origem",
      "São concedidos apenas após aprovação em exame",
      "Excluem pessoas suspeitas de crimes",
    ],
    2,
    "A titularidade decorre da condição humana. Universalidade se opõe à restrição baseada em origem, renda ou condição de suspeito.",
  ],
  [
    "dignidade",
    2,
    "A Declaração Universal dos Direitos Humanos foi proclamada em:",
    [
      "1789, pelo parlamento brasileiro",
      "1824, pelo Império do Brasil",
      "1948, pela Assembleia Geral da ONU",
      "1964, pelo governo brasileiro",
      "1988, pelo Congresso Nacional",
    ],
    2,
    "A DUDH foi proclamada em 1948, no contexto internacional posterior à Segunda Guerra Mundial. Não se confunde com a Constituição brasileira de 1988.",
  ],
  [
    "protecao",
    1,
    "A instalação de recursos de acessibilidade em serviços públicos busca:",
    [
      "Criar barreiras adicionais",
      "Tornar efetivo o exercício de direitos",
      "Eliminar a universalidade dos direitos",
      "Restringir o atendimento às pessoas sem deficiência",
      "Substituir todos os demais direitos",
    ],
    1,
    "Medidas específicas podem remover obstáculos e promover igualdade concreta. Não negam a universalidade: ajudam a realizá-la.",
  ],
  [
    "protecao",
    2,
    "Ao estudar se uma conduta se enquadra em um crime previsto em lei, é necessário:",
    [
      "Presumir que toda falha administrativa é crime",
      "Ignorar os requisitos legais",
      "Comparar os fatos com os elementos exigidos pela norma",
      "Usar apenas a opinião pessoal",
      "Dispensar o texto legal",
    ],
    2,
    "O enquadramento exige analisar os elementos legais. Uma avaliação negativa de uma conduta não substitui a verificação dos requisitos da norma.",
  ],
];
const initialQuestions = rows.map(
  ([lessonId, difficulty, stem, options, answer, explanation], index) => {
    const lesson = LESSONS.find((l) => l.id === lessonId);
    return {
      id: `tello-${String(index + 1).padStart(3, "0")}`,
      lessonId,
      subject: lesson.subject,
      track: lesson.track,
      difficulty,
      stem,
      options,
      answer,
      explanation,
      source: "Autoral · Tello",
      year: 2026,
    };
  },
);
export const QUESTIONS = [...initialQuestions, ...EXPANDED_QUESTIONS, ...VARIABLE_QUESTIONS];
